### ISSUE TITLE
New google-play-services.jar

### ISSUE THREAD

**Issue by chmiiller** [darkdukey/Google-Play-Service-Lite#5]
Hi,
where do you guys find the full google-play-services.jar file? I would need a newer version than the version on the repo. (10.2) How can I find it?

Thanks!

**Comment by ghost** [comment]
https://github.com/darkdukey/Google-Play-Service-Lite/blob/master/pack_gms.sh#L19

```
$ANDROID_SDK_ROOT/extras/google/m2repository/com/google/android/gms
```

**Comment by chmiiller** [comment]
Dude, is in the documentation! How stupid? Sorry about that. Gonna update it and do a PR!

**Comment by chmiiller** [comment]
PR #6
